apiVersion: v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
      app: myapp
      type: front-end
spec:
  template:
    metadata:
      name: ansible-awx
      labels:
          app: ansible-awx
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
## https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

##kubectl create -f pod-define.yml