apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: awx
spec:
  selector:
    matchLabels:
      storagetype: amazonEBS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  volumeName: pv01
  storageClassName: gp2