apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: awx
  labels:
    storagetype: amazonEBS
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01960e5d2084737a8
