apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: awx
  labels:
    storagetype: amazonEBS
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0f23ee2dc832d0402
